package csemana03;

import csemana03.Operaciones_1;
import javax.swing.JOptionPane;

/**
 *
 * @author Jack
 */
public class CEjemplo3 extends javax.swing.JPanel {

    // Declaramos una instancia de la clase Operaciones_1
    Operaciones_1 operaciones;

    public CEjemplo3() {
        initComponents();
        // Inicializamos la instancia de Operaciones_1
        operaciones = new Operaciones_1();
    }

    private void btnCalcular4ActionPerformed(java.awt.event.ActionEvent evt) {
        // Ordenar los datos ingresados
        ordenarDatos();
    }

    private void ordenarDatos() {
        // Obtener los datos del cuadro de entrada
        String texto = txtEntrada.getText();
        if (!texto.isEmpty()) {
            // Dividir los datos por líneas
            String[] datosString = texto.split("\\n");
            // Convertir los datos a números
            double[] datos = new double[datosString.length];
            for (int i = 0; i < datosString.length; i++) {
                datos[i] = Double.parseDouble(datosString[i]);
            }
            // Llamar al método ordenarDatos de la clase Operaciones
            double[] datosOrdenados = operaciones.ordenarDatos(datos);
            // Mostrar los números ordenados en el cuadro de entrada
            StringBuilder resultado = new StringBuilder();
            for (double num : datosOrdenados) {
                resultado.append(num).append("\n");
            }
            txtEntrada.setText(resultado.toString());
        } else {
            JOptionPane.showMessageDialog(this, "No hay datos para ordenar", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private double calcularMedia() {
        double suma = 0;
        int contador = 0;

        // Obtener los datos del cuadro de entrada
        String texto = txtEntrada.getText();

        if (!texto.isEmpty()) {
            // Dividir los datos por líneas
            String[] datosString = texto.split("\\n");

            // Convertir los datos a números y sumarlos
            for (String dato : datosString) {
                suma += Double.parseDouble(dato);
                contador++;
            }

            // Calcular la media
            double media = suma / contador;
            return media;
        } else {
            JOptionPane.showMessageDialog(this, "No hay datos para calcular la media", "Error", JOptionPane.ERROR_MESSAGE);
            return 0;
        }
    }

    private double calcularMediana(double[] numeros) {
        // Implementar el cálculo de la mediana aquí
        return 0;
    }

    private double calcularModa() {
        // Implementar el cálculo de la moda aquí
        return 0;
    }

    private double calcularVarianza() {
        // Implementar el cálculo de la varianza aquí
        return 0;
    }

    private double calcularDesviacionEstandar(double[] numeros) {
        // Implementar el cálculo de la desviación estándar aquí
        return 0;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDatos = new javax.swing.JPanel();
        Datos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtDato = new javax.swing.JTextField();
        btnAgregarDato = new javax.swing.JButton();
        txtEntrada = new javax.swing.JTextArea();
        btnQuitar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        btnOrdenar = new javax.swing.JButton();
        btnArriba = new javax.swing.JButton();
        btnAbajo = new javax.swing.JButton();
        jPanelCalculos = new javax.swing.JPanel();
        Calculos = new javax.swing.JLabel();
        Media = new javax.swing.JLabel();
        Moda = new javax.swing.JLabel();
        Mediana = new javax.swing.JLabel();
        DesviacionEstandar = new javax.swing.JLabel();
        Varianza = new javax.swing.JLabel();
        txtMedia = new javax.swing.JTextField();
        txtMediana = new javax.swing.JTextField();
        txtModa = new javax.swing.JTextField();
        txtVarianza = new javax.swing.JTextField();
        txtDesEstandar = new javax.swing.JTextField();
        Titulo = new javax.swing.JLabel();

        Datos.setText("Datos");

        jLabel1.setText("Dato");

        txtDato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatoActionPerformed(evt);
            }
        });

        btnAgregarDato.setBackground(new java.awt.Color(0, 0, 255));
        btnAgregarDato.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregarDato.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarDato.setText("Agregar");
        btnAgregarDato.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarDato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarDatoActionPerformed(evt);
            }
        });

        txtEntrada.setColumns(20);
        txtEntrada.setRows(5);

        btnQuitar.setBackground(new java.awt.Color(255, 0, 0));
        btnQuitar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuitar.setForeground(new java.awt.Color(255, 255, 255));
        btnQuitar.setText("Quitar");
        btnQuitar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(0, 0, 255));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnCalcular.setBackground(new java.awt.Color(0, 0, 255));
        btnCalcular.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcular.setText("Calcular");
        btnCalcular.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnOrdenar.setBackground(new java.awt.Color(102, 255, 102));
        btnOrdenar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnOrdenar.setForeground(new java.awt.Color(255, 255, 255));
        btnOrdenar.setText("Ordenar");
        btnOrdenar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnArriba.setBackground(new java.awt.Color(51, 255, 255));
        btnArriba.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnArriba.setForeground(new java.awt.Color(255, 255, 255));
        btnArriba.setText("Arriba");
        btnArriba.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnArriba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArribaActionPerformed(evt);
            }
        });

        btnAbajo.setBackground(new java.awt.Color(0, 0, 255));
        btnAbajo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAbajo.setForeground(new java.awt.Color(255, 255, 255));
        btnAbajo.setText("Abajo");
        btnAbajo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbajoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatosLayout = new javax.swing.GroupLayout(jPanelDatos);
        jPanelDatos.setLayout(jPanelDatosLayout);
        jPanelDatosLayout.setHorizontalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Datos))
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnArriba)
                            .addComponent(btnAbajo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDatosLayout.createSequentialGroup()
                                .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnQuitar)
                                    .addComponent(btnLimpiar)))
                            .addGroup(jPanelDatosLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDato, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnAgregarDato)))))
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnOrdenar)
                .addGap(71, 71, 71)
                .addComponent(btnCalcular)
                .addGap(180, 180, 180))
        );
        jPanelDatosLayout.setVerticalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Datos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarDato))
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(btnQuitar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar))
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(btnArriba)
                        .addGap(18, 18, 18)
                        .addComponent(btnAbajo)))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOrdenar)
                    .addComponent(btnCalcular))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Calculos.setText("Calculos");

        Media.setText("Media");

        Moda.setText("Moda");

        Mediana.setText("Mediana");

        DesviacionEstandar.setText("Desviacion estandar");

        Varianza.setText("Varianza");

        txtMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMediaActionPerformed(evt);
            }
        });

        txtMediana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedianaActionPerformed(evt);
            }
        });

        txtModa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModaActionPerformed(evt);
            }
        });

        txtVarianza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVarianzaActionPerformed(evt);
            }
        });

        txtDesEstandar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDesEstandarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCalculosLayout = new javax.swing.GroupLayout(jPanelCalculos);
        jPanelCalculos.setLayout(jPanelCalculosLayout);
        jPanelCalculosLayout.setHorizontalGroup(
            jPanelCalculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCalculosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCalculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Calculos)
                    .addGroup(jPanelCalculosLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanelCalculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Mediana)
                            .addGroup(jPanelCalculosLayout.createSequentialGroup()
                                .addGroup(jPanelCalculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Media)
                                    .addComponent(Moda)
                                    .addComponent(DesviacionEstandar)
                                    .addComponent(Varianza))
                                .addGap(59, 59, 59)
                                .addGroup(jPanelCalculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtVarianza, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMediana, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtModa, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDesEstandar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        jPanelCalculosLayout.setVerticalGroup(
            jPanelCalculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCalculosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Calculos)
                .addGap(35, 35, 35)
                .addGroup(jPanelCalculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Media)
                    .addComponent(txtMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanelCalculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Moda)
                    .addComponent(txtModa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanelCalculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mediana)
                    .addComponent(txtMediana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanelCalculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DesviacionEstandar)
                    .addComponent(txtDesEstandar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanelCalculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Varianza)
                    .addComponent(txtVarianza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(51, 51, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Funciones estadisticas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelCalculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelCalculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatoActionPerformed
         // Obtener el dato ingresado
    String dato = txtDato.getText();
    
    // Agregar el dato al cuadro de entrada
    txtEntrada.append(dato + "\n");
    
    // Limpiar el campo de texto de entrada
    txtDato.setText("");
    }//GEN-LAST:event_txtDatoActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        // Eliminar el último dato ingresado del cuadro de entrada
    String texto = txtEntrada.getText();
    if (!texto.isEmpty()) {
        int index = texto.lastIndexOf("\n");
        if (index >= 0) {
            txtEntrada.setText(texto.substring(0, index));
        } else {
            txtEntrada.setText("");
        }
    }
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // Limpiar el cuadro de entrada
    txtEntrada.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnArribaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArribaActionPerformed
        // Mover el scroll hacia arriba en el cuadro de entrada
    txtEntrada.setCaretPosition(0);
    }//GEN-LAST:event_btnArribaActionPerformed

    private void btnAbajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbajoActionPerformed
        // Mover el scroll hacia abajo en el cuadro de entrada
    txtEntrada.setCaretPosition(txtEntrada.getDocument().getLength());

    }//GEN-LAST:event_btnAbajoActionPerformed

    private void txtMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMediaActionPerformed
        // Calcular la media
    double media = calcularMedia();
    // Mostrar la media en el campo de texto correspondiente
    txtMedia.setText(String.valueOf(media));
    }//GEN-LAST:event_txtMediaActionPerformed

    private void txtMedianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedianaActionPerformed
        
    }//GEN-LAST:event_txtMedianaActionPerformed

    private void txtModaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModaActionPerformed
    
    }//GEN-LAST:event_txtModaActionPerformed

    private void txtVarianzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVarianzaActionPerformed
        
    }//GEN-LAST:event_txtVarianzaActionPerformed

    private void txtDesEstandarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDesEstandarActionPerformed
        
    }//GEN-LAST:event_txtDesEstandarActionPerformed

    private void btnAgregarDatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDatoActionPerformed
        // Obtener el dato ingresado
    String dato = txtDato.getText();
    
    // Agregar el dato al cuadro de entrada
    txtEntrada.append(dato + "\n");
    
    // Limpiar el campo de texto de entrada
    txtDato.setText("");
    }//GEN-LAST:event_btnAgregarDatoActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent ev    txtVarianza.setText(String.valueOf(varianza));//GEN-FIRST:event_btnCalcularActionPerformed
    // Calcular la mediana
    double mediana = calcularMediana();
    // Mostrar la mediana en el campo de texto correspondiente
    txtMediana.setText(String.valueOf(mediana));
    
    // Calcular la moda
    double moda = calcularModa();
    // Mostrar la moda en el campo de texto correspondiente
    txtModa.setText(String.valueOf(moda));
    
    // Calcular la varianza
    double varianza = calcularVarianza();
    // Mostrar la varianza en el campo de texto correspondiente
    txtVarianza.setText(String.valueOf(varianza));
    
    // Calcular la desviación estándar
    double desEstandar = calcularDesviacionEstandar();
    // Mostrar la desviación estándar en el campo de texto correspondiente
    txtDesEstandar.setText(String.valueOf(desEstandar));
    

    }//GEN-LAST:event_btnCalcularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Calculos;
    private javax.swing.JLabel Datos;
    private javax.swing.JLabel DesviacionEstandar;
    private javax.swing.JLabel Media;
    private javax.swing.JLabel Mediana;
    private javax.swing.JLabel Moda;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Varianza;
    private javax.swing.JButton btnAbajo;
    private javax.swing.JButton btnAgregarDato;
    private javax.swing.JButton btnArriba;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelCalculos;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JTextField txtDato;
    private javax.swing.JTextField txtDesEstandar;
    private javax.swing.JTextArea txtEntrada;
    private javax.swing.JTextField txtMedia;
    private javax.swing.JTextField txtMediana;
    private javax.swing.JTextField txtModa;
    private javax.swing.JTextField txtVarianza;
    // End of variables declaration//GEN-END:variables

    private double calcularMediana(double[] numeros) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private double calcularModa(double[] numeros) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private double calcularVarianza(double[] numeros) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private double calcularDesviacionEstandar(double[] numeros) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

  

